List<String> coffeeNames = [
  'Espresso',
  'Cappuccino',
  'Macchiato',
  'Mocha',
  'Latte',
  'Black Coffee',
  'Ristretto',
  'Americano',
  'Long Black',
  'Doppio',
  'Pour Over Coffee',
  'Drip Coffee',
  'Batch Brew',
  'Instant Coffee',
  'AeroPress Coffee',
  'Vacuum Coffee',
  'Immersion Coffee',
  'Milk Based Coffee',
  'Flat White',
  'Caffe Breve',
  'Piccolo Latte',
  'Latte Macchiato',
  'Cortado',
  'Gibraltar',
  'Mocha(Ccino)',
  'Iced And Cold Coffees',
  'Cold Brew Coffee',
  'Nitro Coffee',
  'Japanese Iced Coffee',
  'Espresso Tonic',
  'Strange And Unique Coffees',
  'Turkish Coffee',
  'Vietnamese Coffee',
  'Bulletproof Coffee',
  'Cascara Coffee',
  'Kopi Luwak',
  'Geisha Coffee',
  'Affogato',
  'Irish Coffee'
];
